dragoncurve 0 > dcOut.txt
dragoncurve 1 >> dcOut.txt
dragoncurve 2 >> dcOut.txt
dragoncurve 3 >> dcOut.txt
dragoncurve 4 >> dcOut.txt
dragoncurve 5 >> dcOut.txt
dragoncurve 6 >> dcOut.txt
dragoncurve 7 >> dcOut.txt
dragoncurve 8 >> dcOut.txt
